version: "3"

services:
  openvoice:
    build: .
    image: myshell-openvoice
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN:-}
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD:-}
      - JUPYTER_IP=${JUPYTER_IP:-0.0.0.0}
    command: >
      jupyter lab
      --ip=${JUPYTER_IP:-0.0.0.0}
      --port=8888
      --no-browser
      --allow-root
      --NotebookApp.token=${JUPYTER_TOKEN:-}
      --NotebookApp.password=${JUPYTER_PASSWORD:-}
